# User config
author: "Margaret Ruth Croft"
tagline: "Live Laugh Love"
description: "Margaret Ruth Croft lives and works in New York City."
keywords: "Margaret Ruth, Yoga, Qi Gong, qigong, New York, kid's yoga, children's yoga, brooklyn, yoga for kids, kid's yoga teachers, children's yoga teachers"
email: "margaretcrft@gmail.com"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
